package com.example.subfinder.Entities;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

import java.util.List;

@DynamoDBTable(tableName = "GamesTable")
public class GamesTable {
    private String gameID;
    private String fieldNumber;
    private String time;
    private int numOfSubs;
    private String shirtColor;
    private List<String> listOfSubs;

    public GamesTable() {
    }

    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    public String getGameID() {
        return gameID;
    }

    public void setGameID(String gameID) {
        this.gameID = gameID;
    }

    @DynamoDBAttribute
    public String getFieldNumber() {
        return fieldNumber;
    }

    public void setFieldNumber(String fieldNumber) {
        this.fieldNumber = fieldNumber;
    }

    @DynamoDBAttribute
    public String getTime() {
        return time;
    }

    public void setTime(String time) {
        this.time = time;
    }

    @DynamoDBAttribute
    public int getNumOfSubs() {
        return numOfSubs;
    }

    public void setNumOfSubs(int numOfSubs) {
        this.numOfSubs = numOfSubs;
    }

    @DynamoDBAttribute
    public String getShirtColor() {
        return shirtColor;
    }

    public void setShirtColor(String shirtColor) {
        this.shirtColor = shirtColor;
    }

    @DynamoDBAttribute
    public List<String> getListOfSubs() {
        return listOfSubs;
    }

    public void setListOfSubs(List<String> listOfSubs) {
        this.listOfSubs = listOfSubs;
    }
}
